### ISSUE TITLE
Canonot find module 'config'

### ISSUE THREAD

**Issue by 0sh0** [fzaninotto/screenshot-as-a-service#76]
I get that error when I try to run the app

C:...\screenshot>node app

module.js:340
    throw err;
          ^
Error: Cannot find module 'config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\screenshot\app.j
s:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by lukesnowden** [comment]
npm install?

**Comment by Priyalc** [comment]
Hi, 

I am also getting the same error. I have installed npm though..

![image](https://cloud.githubusercontent.com/assets/11949336/10105740/5b969794-637e-11e5-8350-72d89c4dbc3c.png)

any solution?

**Comment by fadewaif** [comment]
same problem
